name: scroll_behavior
version: 0.0.1
description: work in progress
author: Remi Rousselet <darky12s@gmail.com>
homepage: https://github.com/rrousselGit/scroll-behavior

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
